import type {Metadata} from "next";
import "./globals.css";
import {Toaster} from "@/components/ui/sonner";
import {Providers} from "@/components/providers";
import localFont from "next/font/local";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const IranSansFont = localFont({
    src: [
        {
            path: './fonts/IranSans/IRANSansUltraLight.woff2',
            style: "normal",
            weight: "200"
        },
        {
            path: './fonts/IranSans/IRANSansLight.woff2',
            style: "normal",
            weight: "300"
        },
        {
            path: './fonts/IranSans/IRANSansNormal.woff2',
            style: "normal",
            weight: "400"
        },
        {
            path: './fonts/IranSans/IRANSansMedium.woff2',
            style: "normal",
            weight: "500"
        },
        {
            path: './fonts/IranSans/IRANSansBold.woff2',
            style: "normal",
            weight: "700"
        },
        {
            path: './fonts/IranSans/IRANSansBlack.woff2',
            style: "normal",
            weight: "900"
        },
    ],
    variable: '--font-iran-sans',
})

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir={"rtl"}>
        <body
            className={`${IranSansFont.className} antialiased`}
        >
        <Providers>
            <main
                className={"min-h-screen bg-background text-foreground flex flex-col items-center justify-center "}>{children}</main>
            <Toaster richColors toastOptions={{
                className: IranSansFont.className
            }}/>
        </Providers>
        </body>
        </html>
    );
}
